/*jslint */
/*global AdobeEdge: false, window: false, document: false, console:false, alert: false */
(function (compId) {

    "use strict";
    var im='images/',
        aud='media/',
        vid='media/',
        js='js/',
        fonts = {
        },
        opts = {
            'gAudioPreloadPreference': 'auto',
            'gVideoPreloadPreference': 'auto'
        },
        resources = [
        ],
        scripts = [
        ],
        symbols = {
            "stage": {
                version: "6.0.0",
                minimumCompatibleVersion: "5.0.0",
                build: "6.0.0.400",
                scaleToFit: "none",
                centerStage: "none",
                resizeInstances: false,
                content: {
                    dom: [
                        {
                            id: 'REALBG',
                            type: 'image',
                            rect: ['0px', '0px', '374px', '226px', 'auto', 'auto'],
                            fill: ["rgba(0,0,0,0)",im+"101000101.jpg",'0px','0px']
                        },
                        {
                            id: 'Group',
                            type: 'group',
                            rect: ['374px', '30px', '143px', '198px', 'auto', 'auto'],
                            opacity: '0',
                            c: [
                            {
                                id: '_012002',
                                type: 'image',
                                rect: ['61px', '0px', '56px', '12px', 'auto', 'auto'],
                                fill: ["rgba(0,0,0,0)",im+"01200.jpg",'0px','0px']
                            },
                            {
                                id: '_012001',
                                type: 'image',
                                rect: ['48px', '12px', '81px', '104px', 'auto', 'auto'],
                                fill: ["rgba(0,0,0,0)",im+"012001.jpg",'0px','0px']
                            },
                            {
                                id: '_0120022',
                                type: 'image',
                                rect: ['0px', '115px', '143px', '83px', 'auto', 'auto'],
                                fill: ["rgba(0,0,0,0)",im+"012002.jpg",'0px','0px']
                            }]
                        },
                        {
                            id: 'TOPBLACK',
                            type: 'rect',
                            rect: ['0px', '0px', '374px', '23px', 'auto', 'auto'],
                            fill: ["rgba(0,0,0,1.00)"],
                            stroke: [0,"rgba(0,0,0,0.00)","none"]
                        },
                        {
                            id: 'D_11_subtitle',
                            display: 'none',
                            type: 'image',
                            rect: ['64px', '142px', '32.3%', '5.3%', 'auto', 'auto'],
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"87451514110000_03.png",'0px','0px'],
                            boxShadow: ["", 0, 0, 0, 0, "rgba(0,0,0,0)"]
                        },
                        {
                            id: 'title',
                            type: 'image',
                            rect: ['4px', '6px', '106px', '31px', 'auto', 'auto'],
                            fill: ["rgba(0,0,0,0)",im+"52045825555555_03.png",'0px','0px']
                        },
                        {
                            id: 'PD',
                            type: 'image',
                            rect: ['216px', '71px', '154px', '149px', 'auto', 'auto'],
                            fill: ["rgba(0,0,0,0)",im+"9751152101_07.png",'0px','0px']
                        },
                        {
                            id: 'topsubtitle',
                            type: 'image',
                            rect: ['113px', '12px', '203px', '18px', 'auto', 'auto'],
                            fill: ["rgba(0,0,0,0)",im+"1545150210151510_03.jpg",'0px','0px']
                        },
                        {
                            id: 'seventypercent',
                            type: 'image',
                            rect: ['133px', '101px', '13px', '17px', 'auto', 'auto'],
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"54512054154.png",'0px','0px']
                        },
                        {
                            id: '_2cuttitle1',
                            type: 'group',
                            rect: ['-214px', '82px', '210', '54', 'auto', 'auto'],
                            c: [
                            {
                                id: '_151510010',
                                type: 'image',
                                rect: ['0px', '0px', '107px', '54px', 'auto', 'auto'],
                                fill: ["rgba(0,0,0,0)",im+"151510010.png",'0px','0px']
                            },
                            {
                                id: '_4515201',
                                type: 'image',
                                rect: ['157px', '0px', '53px', '54px', 'auto', 'auto'],
                                fill: ["rgba(0,0,0,0)",im+"4515201.png",'0px','0px']
                            }]
                        },
                        {
                            id: '_2cuttitle_5_01',
                            type: 'image',
                            rect: ['21px', '93px', '11px', '15px', 'auto', 'auto'],
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"1545150210151510_07.png",'0px','0px'],
                            boxShadow: ["", 0, 0, 0, 0, "rgba(0,0,0,0)"]
                        },
                        {
                            id: '_2cuttitle_5_02',
                            type: 'image',
                            rect: ['147px', '107px', '11px', '15px', 'auto', 'auto'],
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"1545150210151510_07.png",'0px','0px'],
                            boxShadow: ["", 0, 0, 0, 0, "rgba(0,0,0,0)"]
                        },
                        {
                            id: 'giftcard',
                            type: 'image',
                            rect: ['-78px', '151px', '79px', '18px', 'auto', 'auto'],
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"1545150210151510_17.png",'0px','0px']
                        },
                        {
                            id: 'gift1700',
                            type: 'image',
                            rect: ['154px', '143px', '95px', '30px', 'auto', 'auto'],
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"1545150210151510_15.png",'0px','0px']
                        },
                        {
                            id: 'number1',
                            type: 'image',
                            rect: ['23px', '152px', '7px', '7px', 'auto', 'auto'],
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"9751152101_20.png",'0px','0px']
                        },
                        {
                            id: 'jomalone',
                            type: 'image',
                            rect: ['125px', '157px', '95px', '30px', 'auto', 'auto'],
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"451010002122524524_03.png",'0px','0px']
                        },
                        {
                            id: 'PLUS',
                            type: 'image',
                            rect: ['-180px', '154px', '59px', '18px', 'auto', 'auto'],
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"451010002122524524_09.png",'0px','0px']
                        },
                        {
                            id: 'number2',
                            type: 'image',
                            rect: ['-208px', '148px', '24px', '24px', 'auto', 'auto'],
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"451010002122524524_06.png",'0px','0px']
                        },
                        {
                            id: 'BTN',
                            type: 'image',
                            rect: ['-117px', '182px', '103px', '28px', 'auto', 'auto'],
                            fill: ["rgba(0,0,0,0)",im+"14521014444_03.png",'0px','0px']
                        },
                        {
                            id: 'redtrng',
                            type: 'image',
                            rect: ['195px', '190px', '6px', '11px', 'auto', 'auto'],
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"15100114555_03.gif",'0px','0px']
                        },
                        {
                            id: 'redtrng2',
                            type: 'image',
                            rect: ['203px', '190px', '6px', '11px', 'auto', 'auto'],
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"15100114555_03.gif",'0px','0px']
                        },
                        {
                            id: '_100bat',
                            type: 'image',
                            rect: ['138px', '141px', '73px', '31px', 'auto', 'auto'],
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"84785101111111_03.png",'0px','0px']
                        },
                        {
                            id: 'TODAYPLUS',
                            type: 'image',
                            rect: ['-100px', '151px', '92px', '21px', 'auto', 'auto'],
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"84785101111111_09.png",'0px','0px']
                        },
                        {
                            id: 'number3',
                            type: 'image',
                            rect: ['11px', '148px', '24px', '24px', 'auto', 'auto'],
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"84785101111111_06.png",'0px','0px']
                        },
                        {
                            id: 'Group2',
                            type: 'group',
                            rect: ['374px', '43px', '143px', '198px', 'auto', 'auto'],
                            opacity: '1',
                            c: [
                            {
                                id: '_54151010112',
                                type: 'image',
                                rect: ['0px', '130px', '157px', '55px', 'auto', 'auto'],
                                fill: ["rgba(0,0,0,0)",im+"54151010112.jpg",'0px','0px']
                            },
                            {
                                id: '_54151010111',
                                type: 'image',
                                rect: ['23px', '105px', '8px', '25px', 'auto', 'auto'],
                                fill: ["rgba(0,0,0,0)",im+"54151010111.jpg",'0px','0px']
                            },
                            {
                                id: '_54151010110',
                                type: 'image',
                                rect: ['31px', '0px', '103px', '130px', 'auto', 'auto'],
                                fill: ["rgba(0,0,0,0)",im+"54151010110.jpg",'0px','0px']
                            }]
                        }
                    ],
                    style: {
                        '${Stage}': {
                            isStage: true,
                            rect: ['null', 'null', '374px', '226px', 'auto', 'auto'],
                            overflow: 'hidden',
                            fill: ["rgba(255,255,255,1)"]
                        }
                    }
                },
                timeline: {
                    duration: 8500,
                    autoPlay: true,
                    data: [
                        [
                            "eid427",
                            "left",
                            3343,
                            196,
                            "swing",
                            "${gift1700}",
                            '154px',
                            '121px'
                        ],
                        [
                            "eid473",
                            "left",
                            4500,
                            250,
                            "swing",
                            "${gift1700}",
                            '121px',
                            '-108px'
                        ],
                        [
                            "eid892",
                            "height",
                            250,
                            0,
                            "linear",
                            "${title}",
                            '68px',
                            '68px'
                        ],
                        [
                            "eid902",
                            "height",
                            2500,
                            250,
                            "easeInBack",
                            "${title}",
                            '68px',
                            '31px'
                        ],
                        [
                            "eid507",
                            "left",
                            4500,
                            250,
                            "swing",
                            "${number2}",
                            '-208px',
                            '10px'
                        ],
                        [
                            "eid550",
                            "left",
                            6000,
                            250,
                            "swing",
                            "${number2}",
                            '10px',
                            '-210px'
                        ],
                        [
                            "eid426",
                            "opacity",
                            3343,
                            196,
                            "swing",
                            "${gift1700}",
                            '0',
                            '1'
                        ],
                        [
                            "eid476",
                            "opacity",
                            4500,
                            250,
                            "swing",
                            "${gift1700}",
                            '1',
                            '0'
                        ],
                        [
                            "eid370",
                            "top",
                            2843,
                            250,
                            "easeInBack",
                            "${_2cuttitle_5_02}",
                            '107px',
                            '93px'
                        ],
                        [
                            "eid371",
                            "top",
                            3093,
                            250,
                            "easeInBack",
                            "${_2cuttitle_5_02}",
                            '93px',
                            '83px'
                        ],
                        [
                            "eid372",
                            "top",
                            3343,
                            250,
                            "easeInBack",
                            "${_2cuttitle_5_02}",
                            '83px',
                            '93px'
                        ],
                        [
                            "eid894",
                            "top",
                            250,
                            750,
                            "easeInBack",
                            "${title}",
                            '71px',
                            '72px'
                        ],
                        [
                            "eid905",
                            "top",
                            2500,
                            250,
                            "easeInBack",
                            "${title}",
                            '72px',
                            '6px'
                        ],
                        [
                            "eid1084",
                            "left",
                            2500,
                            250,
                            "easeInQuad",
                            "${Group2}",
                            '374px',
                            '218px'
                        ],
                        [
                            "eid1093",
                            "left",
                            6000,
                            250,
                            "easeInQuad",
                            "${Group2}",
                            '218px',
                            '374px'
                        ],
                        [
                            "eid567",
                            "width",
                            6000,
                            0,
                            "swing",
                            "${number3}",
                            '24px',
                            '24px'
                        ],
                        [
                            "eid579",
                            "width",
                            6250,
                            0,
                            "swing",
                            "${number3}",
                            '24px',
                            '24px'
                        ],
                        [
                            "eid939",
                            "top",
                            2649,
                            250,
                            "easeInBack",
                            "${seventypercent}",
                            '101px',
                            '82px'
                        ],
                        [
                            "eid677",
                            "top",
                            3147,
                            0,
                            "swing",
                            "${giftcard}",
                            '151px',
                            '151px'
                        ],
                        [
                            "eid678",
                            "top",
                            3343,
                            0,
                            "swing",
                            "${giftcard}",
                            '151px',
                            '151px'
                        ],
                        [
                            "eid955",
                            "top",
                            4500,
                            0,
                            "swing",
                            "${giftcard}",
                            '151px',
                            '151px'
                        ],
                        [
                            "eid956",
                            "top",
                            4750,
                            0,
                            "swing",
                            "${giftcard}",
                            '151px',
                            '151px'
                        ],
                        [
                            "eid921",
                            "top",
                            2500,
                            0,
                            "swing",
                            "${_2cuttitle1}",
                            '82px',
                            '82px'
                        ],
                        [
                            "eid922",
                            "top",
                            2750,
                            0,
                            "swing",
                            "${_2cuttitle1}",
                            '82px',
                            '82px'
                        ],
                        [
                            "eid743",
                            "top",
                            250,
                            750,
                            "easeInBack",
                            "${D_11_subtitle}",
                            '147px',
                            '141px'
                        ],
                        [
                            "eid748",
                            "top",
                            1000,
                            250,
                            "easeInBack",
                            "${D_11_subtitle}",
                            '141px',
                            '144px'
                        ],
                        [
                            "eid749",
                            "top",
                            1250,
                            500,
                            "easeInBack",
                            "${D_11_subtitle}",
                            '144px',
                            '142px'
                        ],
                        [
                            "eid377",
                            "left",
                            2843,
                            250,
                            "easeInBack",
                            "${_2cuttitle_5_02}",
                            '147px',
                            '138px'
                        ],
                        [
                            "eid384",
                            "left",
                            3343,
                            0,
                            "swing",
                            "${_2cuttitle_5_02}",
                            '138px',
                            '138px'
                        ],
                        [
                            "eid385",
                            "left",
                            3593,
                            0,
                            "swing",
                            "${_2cuttitle_5_02}",
                            '138px',
                            '138px'
                        ],
                        [
                            "eid511",
                            "left",
                            5000,
                            250,
                            "swing",
                            "${jomalone}",
                            '125px',
                            '103px'
                        ],
                        [
                            "eid548",
                            "left",
                            6000,
                            250,
                            "swing",
                            "${jomalone}",
                            '103px',
                            '-139px'
                        ],
                        [
                            "eid566",
                            "width",
                            6250,
                            0,
                            "swing",
                            "${TODAYPLUS}",
                            '92px',
                            '92px'
                        ],
                        [
                            "eid578",
                            "width",
                            6500,
                            0,
                            "swing",
                            "${TODAYPLUS}",
                            '92px',
                            '92px'
                        ],
                        [
                            "eid628",
                            "filter.hue-rotate",
                            7000,
                            0,
                            "swing",
                            "${BTN}",
                            '0deg',
                            '0deg'
                        ],
                        [
                            "eid565",
                            "height",
                            6500,
                            0,
                            "swing",
                            "${_100bat}",
                            '31px',
                            '31px'
                        ],
                        [
                            "eid577",
                            "height",
                            6750,
                            0,
                            "swing",
                            "${_100bat}",
                            '31px',
                            '31px'
                        ],
                        [
                            "eid631",
                            "width",
                            6750,
                            0,
                            "swing",
                            "${BTN}",
                            '103px',
                            '103px'
                        ],
                        [
                            "eid632",
                            "width",
                            7000,
                            0,
                            "swing",
                            "${BTN}",
                            '103px',
                            '103px'
                        ],
                        [
                            "eid601",
                            "opacity",
                            6250,
                            250,
                            "swing",
                            "${TODAYPLUS}",
                            '0',
                            '1'
                        ],
                        [
                            "eid744",
                            "width",
                            250,
                            750,
                            "easeInBack",
                            "${D_11_subtitle}",
                            '32.25%',
                            '67.92%'
                        ],
                        [
                            "eid750",
                            "width",
                            1000,
                            250,
                            "easeInBack",
                            "${D_11_subtitle}",
                            '67.92%',
                            '45.14%'
                        ],
                        [
                            "eid751",
                            "width",
                            1250,
                            500,
                            "easeInBack",
                            "${D_11_subtitle}",
                            '45.14%',
                            '58.83%'
                        ],
                        [
                            "eid597",
                            "left",
                            6250,
                            250,
                            "swing",
                            "${TODAYPLUS}",
                            '-100px',
                            '40px'
                        ],
                        [
                            "eid480",
                            "width",
                            4500,
                            0,
                            "swing",
                            "${number2}",
                            '24px',
                            '24px'
                        ],
                        [
                            "eid506",
                            "width",
                            4750,
                            0,
                            "swing",
                            "${number2}",
                            '24px',
                            '24px'
                        ],
                        [
                            "eid520",
                            "width",
                            6000,
                            0,
                            "swing",
                            "${number2}",
                            '24px',
                            '24px'
                        ],
                        [
                            "eid537",
                            "width",
                            6250,
                            0,
                            "swing",
                            "${number2}",
                            '24px',
                            '24px'
                        ],
                        [
                            "eid940",
                            "opacity",
                            2649,
                            250,
                            "easeInBack",
                            "${seventypercent}",
                            '0',
                            '1'
                        ],
                        [
                            "eid289",
                            "display",
                            250,
                            0,
                            "easeInCirc",
                            "${D_11_subtitle}",
                            'none',
                            'block'
                        ],
                        [
                            "eid512",
                            "top",
                            5000,
                            250,
                            "swing",
                            "${jomalone}",
                            '157px',
                            '146px'
                        ],
                        [
                            "eid1045",
                            "top",
                            6000,
                            250,
                            "swing",
                            "${jomalone}",
                            '146px',
                            '142px'
                        ],
                        [
                            "eid600",
                            "opacity",
                            6000,
                            250,
                            "swing",
                            "${number3}",
                            '0',
                            '1'
                        ],
                        [
                            "eid400",
                            "opacity",
                            3000,
                            250,
                            "swing",
                            "${number1}",
                            '0',
                            '1'
                        ],
                        [
                            "eid475",
                            "opacity",
                            4500,
                            250,
                            "swing",
                            "${number1}",
                            '1',
                            '0'
                        ],
                        [
                            "eid596",
                            "left",
                            6000,
                            250,
                            "swing",
                            "${number3}",
                            '-214px',
                            '11px'
                        ],
                        [
                            "eid638",
                            "filter.invert",
                            7000,
                            0,
                            "swing",
                            "${BTN}",
                            '0',
                            '0'
                        ],
                        [
                            "eid412",
                            "left",
                            3147,
                            196,
                            "swing",
                            "${giftcard}",
                            '-78px',
                            '38px'
                        ],
                        [
                            "eid471",
                            "left",
                            4500,
                            250,
                            "swing",
                            "${giftcard}",
                            '38px',
                            '-182px'
                        ],
                        [
                            "eid424",
                            "top",
                            3343,
                            196,
                            "swing",
                            "${gift1700}",
                            '157px',
                            '143px'
                        ],
                        [
                            "eid965",
                            "top",
                            4500,
                            0,
                            "swing",
                            "${gift1700}",
                            '143px',
                            '143px'
                        ],
                        [
                            "eid966",
                            "top",
                            4750,
                            0,
                            "swing",
                            "${gift1700}",
                            '143px',
                            '143px'
                        ],
                        [
                            "eid1006",
                            "left",
                            0,
                            500,
                            "easeInQuad",
                            "${Group}",
                            '374px',
                            '231px'
                        ],
                        [
                            "eid1015",
                            "left",
                            2500,
                            250,
                            "easeInQuad",
                            "${Group}",
                            '231px',
                            '374px'
                        ],
                        [
                            "eid937",
                            "width",
                            2649,
                            250,
                            "easeInBack",
                            "${seventypercent}",
                            '13px',
                            '39px'
                        ],
                        [
                            "eid261",
                            "top",
                            3000,
                            0,
                            "swing",
                            "${topsubtitle}",
                            '12px',
                            '12px'
                        ],
                        [
                            "eid563",
                            "height",
                            6000,
                            0,
                            "swing",
                            "${number3}",
                            '24px',
                            '24px'
                        ],
                        [
                            "eid575",
                            "height",
                            6250,
                            0,
                            "swing",
                            "${number3}",
                            '24px',
                            '24px'
                        ],
                        [
                            "eid1039",
                            "width",
                            4750,
                            0,
                            "linear",
                            "${PLUS}",
                            '59px',
                            '59px'
                        ],
                        [
                            "eid1041",
                            "width",
                            5000,
                            0,
                            "linear",
                            "${PLUS}",
                            '59px',
                            '59px'
                        ],
                        [
                            "eid1042",
                            "width",
                            6000,
                            0,
                            "linear",
                            "${PLUS}",
                            '59px',
                            '59px'
                        ],
                        [
                            "eid1043",
                            "width",
                            6250,
                            0,
                            "linear",
                            "${PLUS}",
                            '59px',
                            '59px'
                        ],
                        [
                            "eid373",
                            "height",
                            2843,
                            250,
                            "easeInBack",
                            "${_2cuttitle_5_02}",
                            '15px',
                            '43px'
                        ],
                        [
                            "eid374",
                            "height",
                            3093,
                            250,
                            "easeInBack",
                            "${_2cuttitle_5_02}",
                            '43px',
                            '53px'
                        ],
                        [
                            "eid375",
                            "height",
                            3343,
                            250,
                            "easeInBack",
                            "${_2cuttitle_5_02}",
                            '53px',
                            '43px'
                        ],
                        [
                            "eid708",
                            "top",
                            6750,
                            0,
                            "swing",
                            "${BTN}",
                            '182px',
                            '182px'
                        ],
                        [
                            "eid709",
                            "top",
                            7000,
                            0,
                            "swing",
                            "${BTN}",
                            '182px',
                            '182px'
                        ],
                        [
                            "eid517",
                            "width",
                            5000,
                            250,
                            "swing",
                            "${jomalone}",
                            '38px',
                            '95px'
                        ],
                        [
                            "eid1031",
                            "width",
                            6000,
                            0,
                            "linear",
                            "${jomalone}",
                            '95px',
                            '95px'
                        ],
                        [
                            "eid1032",
                            "width",
                            6250,
                            0,
                            "linear",
                            "${jomalone}",
                            '95px',
                            '95px'
                        ],
                        [
                            "eid745",
                            "left",
                            250,
                            750,
                            "easeInBack",
                            "${D_11_subtitle}",
                            '64px',
                            '-12px'
                        ],
                        [
                            "eid752",
                            "left",
                            1000,
                            250,
                            "easeInBack",
                            "${D_11_subtitle}",
                            '-12px',
                            '27px'
                        ],
                        [
                            "eid753",
                            "left",
                            1250,
                            500,
                            "easeInBack",
                            "${D_11_subtitle}",
                            '27px',
                            '11px'
                        ],
                        [
                            "eid290",
                            "left",
                            2500,
                            250,
                            "easeInCirc",
                            "${D_11_subtitle}",
                            '11px',
                            '-229px'
                        ],
                        [
                            "eid630",
                            "left",
                            6750,
                            250,
                            "swing",
                            "${BTN}",
                            '-117px',
                            '109px'
                        ],
                        [
                            "eid893",
                            "left",
                            250,
                            750,
                            "easeInBack",
                            "${title}",
                            '-243px',
                            '9px'
                        ],
                        [
                            "eid895",
                            "left",
                            1000,
                            250,
                            "easeInBack",
                            "${title}",
                            '9px',
                            '-12px'
                        ],
                        [
                            "eid896",
                            "left",
                            1250,
                            500,
                            "easeInBack",
                            "${title}",
                            '-12px',
                            '9px'
                        ],
                        [
                            "eid904",
                            "left",
                            2500,
                            250,
                            "easeInBack",
                            "${title}",
                            '9px',
                            '4px'
                        ],
                        [
                            "eid351",
                            "height",
                            2593,
                            250,
                            "swing",
                            "${_2cuttitle_5_01}",
                            '15px',
                            '43px'
                        ],
                        [
                            "eid364",
                            "height",
                            2843,
                            250,
                            "swing",
                            "${_2cuttitle_5_01}",
                            '43px',
                            '53px'
                        ],
                        [
                            "eid365",
                            "height",
                            3093,
                            250,
                            "swing",
                            "${_2cuttitle_5_01}",
                            '53px',
                            '43px'
                        ],
                        [
                            "eid742",
                            "height",
                            250,
                            750,
                            "easeInBack",
                            "${D_11_subtitle}",
                            '5.26%',
                            '11.24%'
                        ],
                        [
                            "eid746",
                            "height",
                            1000,
                            250,
                            "easeInBack",
                            "${D_11_subtitle}",
                            '11.24%',
                            '7.47%'
                        ],
                        [
                            "eid747",
                            "height",
                            1250,
                            500,
                            "easeInBack",
                            "${D_11_subtitle}",
                            '7.47%',
                            '9.73%'
                        ],
                        [
                            "eid945",
                            "width",
                            3147,
                            0,
                            "swing",
                            "${giftcard}",
                            '79px',
                            '79px'
                        ],
                        [
                            "eid949",
                            "width",
                            3343,
                            0,
                            "swing",
                            "${giftcard}",
                            '79px',
                            '79px'
                        ],
                        [
                            "eid950",
                            "width",
                            4500,
                            0,
                            "swing",
                            "${giftcard}",
                            '79px',
                            '79px'
                        ],
                        [
                            "eid951",
                            "width",
                            4750,
                            0,
                            "swing",
                            "${giftcard}",
                            '79px',
                            '79px'
                        ],
                        [
                            "eid918",
                            "opacity",
                            2500,
                            250,
                            "swing",
                            "${_2cuttitle1}",
                            '0',
                            '1'
                        ],
                        [
                            "eid637",
                            "filter.saturate",
                            7000,
                            0,
                            "swing",
                            "${BTN}",
                            '1',
                            '1'
                        ],
                        [
                            "eid700",
                            "top",
                            6250,
                            0,
                            "swing",
                            "${TODAYPLUS}",
                            '151px',
                            '151px'
                        ],
                        [
                            "eid586",
                            "top",
                            6500,
                            0,
                            "swing",
                            "${TODAYPLUS}",
                            '151px',
                            '151px'
                        ],
                        [
                            "eid627",
                            "filter.contrast",
                            7000,
                            0,
                            "swing",
                            "${BTN}",
                            '1',
                            '1'
                        ],
                        [
                            "eid683",
                            "top",
                            4500,
                            0,
                            "swing",
                            "${number2}",
                            '148px',
                            '148px'
                        ],
                        [
                            "eid684",
                            "top",
                            4750,
                            0,
                            "swing",
                            "${number2}",
                            '148px',
                            '148px'
                        ],
                        [
                            "eid688",
                            "top",
                            6000,
                            0,
                            "swing",
                            "${number2}",
                            '148px',
                            '148px'
                        ],
                        [
                            "eid689",
                            "top",
                            6250,
                            0,
                            "swing",
                            "${number2}",
                            '148px',
                            '148px'
                        ],
                        [
                            "eid353",
                            "width",
                            2593,
                            250,
                            "swing",
                            "${_2cuttitle_5_01}",
                            '11px',
                            '31px'
                        ],
                        [
                            "eid368",
                            "width",
                            2843,
                            250,
                            "swing",
                            "${_2cuttitle_5_01}",
                            '31px',
                            '38px'
                        ],
                        [
                            "eid369",
                            "width",
                            3093,
                            250,
                            "swing",
                            "${_2cuttitle_5_01}",
                            '38px',
                            '31px'
                        ],
                        [
                            "eid562",
                            "height",
                            6250,
                            0,
                            "swing",
                            "${TODAYPLUS}",
                            '21px',
                            '21px'
                        ],
                        [
                            "eid574",
                            "height",
                            6500,
                            0,
                            "swing",
                            "${TODAYPLUS}",
                            '21px',
                            '21px'
                        ],
                        [
                            "eid599",
                            "opacity",
                            6500,
                            250,
                            "swing",
                            "${_100bat}",
                            '0',
                            '1'
                        ],
                        [
                            "eid891",
                            "width",
                            250,
                            0,
                            "linear",
                            "${title}",
                            '233px',
                            '233px'
                        ],
                        [
                            "eid903",
                            "width",
                            2500,
                            250,
                            "easeInBack",
                            "${title}",
                            '233px',
                            '106px'
                        ],
                        [
                            "eid936",
                            "height",
                            2649,
                            250,
                            "easeInBack",
                            "${seventypercent}",
                            '17px',
                            '54px'
                        ],
                        [
                            "eid396",
                            "height",
                            3000,
                            250,
                            "swing",
                            "${number1}",
                            '7px',
                            '23px'
                        ],
                        [
                            "eid454",
                            "height",
                            4500,
                            0,
                            "swing",
                            "${number1}",
                            '23px',
                            '23px'
                        ],
                        [
                            "eid458",
                            "height",
                            4750,
                            0,
                            "swing",
                            "${number1}",
                            '23px',
                            '23px'
                        ],
                        [
                            "eid514",
                            "opacity",
                            4750,
                            250,
                            "swing",
                            "${PLUS}",
                            '0',
                            '1'
                        ],
                        [
                            "eid552",
                            "opacity",
                            6000,
                            250,
                            "swing",
                            "${PLUS}",
                            '1',
                            '0'
                        ],
                        [
                            "eid354",
                            "opacity",
                            2593,
                            250,
                            "swing",
                            "${_2cuttitle_5_01}",
                            '0',
                            '1'
                        ],
                        [
                            "eid425",
                            "width",
                            3343,
                            196,
                            "swing",
                            "${gift1700}",
                            '21px',
                            '95px'
                        ],
                        [
                            "eid961",
                            "width",
                            4500,
                            0,
                            "swing",
                            "${gift1700}",
                            '95px',
                            '95px'
                        ],
                        [
                            "eid962",
                            "width",
                            4750,
                            0,
                            "swing",
                            "${gift1700}",
                            '95px',
                            '95px'
                        ],
                        [
                            "eid1026",
                            "opacity",
                            0,
                            500,
                            "easeInQuad",
                            "${Group}",
                            '0',
                            '1'
                        ],
                        [
                            "eid1024",
                            "opacity",
                            2500,
                            250,
                            "easeInQuad",
                            "${Group}",
                            '1',
                            '0'
                        ],
                        [
                            "eid999",
                            "height",
                            0,
                            0,
                            "easeInBack",
                            "${Group}",
                            '198px',
                            '198px'
                        ],
                        [
                            "eid1005",
                            "height",
                            500,
                            0,
                            "easeInBack",
                            "${Group}",
                            '198px',
                            '198px'
                        ],
                        [
                            "eid1008",
                            "height",
                            2500,
                            0,
                            "easeInBack",
                            "${Group}",
                            '198px',
                            '198px'
                        ],
                        [
                            "eid1012",
                            "height",
                            2750,
                            0,
                            "easeInBack",
                            "${Group}",
                            '198px',
                            '198px'
                        ],
                        [
                            "eid355",
                            "left",
                            2593,
                            250,
                            "swing",
                            "${_2cuttitle_5_01}",
                            '21px',
                            '11px'
                        ],
                        [
                            "eid358",
                            "left",
                            3093,
                            0,
                            "swing",
                            "${_2cuttitle_5_01}",
                            '11px',
                            '11px'
                        ],
                        [
                            "eid362",
                            "left",
                            3343,
                            0,
                            "swing",
                            "${_2cuttitle_5_01}",
                            '11px',
                            '11px'
                        ],
                        [
                            "eid302",
                            "left",
                            6000,
                            250,
                            "easeInBack",
                            "${PD}",
                            '388px',
                            '216px'
                        ],
                        [
                            "eid938",
                            "left",
                            2649,
                            250,
                            "easeInBack",
                            "${seventypercent}",
                            '133px',
                            '119px'
                        ],
                        [
                            "eid411",
                            "opacity",
                            3147,
                            196,
                            "swing",
                            "${giftcard}",
                            '0',
                            '1'
                        ],
                        [
                            "eid474",
                            "opacity",
                            4500,
                            250,
                            "swing",
                            "${giftcard}",
                            '1',
                            '0'
                        ],
                        [
                            "eid481",
                            "height",
                            4500,
                            0,
                            "swing",
                            "${number2}",
                            '24px',
                            '24px'
                        ],
                        [
                            "eid505",
                            "height",
                            4750,
                            0,
                            "swing",
                            "${number2}",
                            '24px',
                            '24px'
                        ],
                        [
                            "eid532",
                            "height",
                            6000,
                            0,
                            "swing",
                            "${number2}",
                            '24px',
                            '24px'
                        ],
                        [
                            "eid536",
                            "height",
                            6250,
                            0,
                            "swing",
                            "${number2}",
                            '24px',
                            '24px'
                        ],
                        [
                            "eid513",
                            "opacity",
                            4500,
                            250,
                            "swing",
                            "${number2}",
                            '0',
                            '1'
                        ],
                        [
                            "eid553",
                            "opacity",
                            6000,
                            250,
                            "swing",
                            "${number2}",
                            '1',
                            '0'
                        ],
                        [
                            "eid515",
                            "opacity",
                            5000,
                            250,
                            "swing",
                            "${jomalone}",
                            '0',
                            '1'
                        ],
                        [
                            "eid551",
                            "opacity",
                            6000,
                            250,
                            "swing",
                            "${jomalone}",
                            '1',
                            '0'
                        ],
                        [
                            "eid398",
                            "left",
                            3000,
                            250,
                            "swing",
                            "${number1}",
                            '23px',
                            '10px'
                        ],
                        [
                            "eid472",
                            "left",
                            4500,
                            250,
                            "swing",
                            "${number1}",
                            '10px',
                            '-210px'
                        ],
                        [
                            "eid635",
                            "height",
                            6750,
                            0,
                            "swing",
                            "${BTN}",
                            '28px',
                            '28px'
                        ],
                        [
                            "eid636",
                            "height",
                            7000,
                            0,
                            "swing",
                            "${BTN}",
                            '28px',
                            '28px'
                        ],
                        [
                            "eid646",
                            "opacity",
                            7250,
                            0,
                            "swing",
                            "${redtrng2}",
                            '0',
                            '0'
                        ],
                        [
                            "eid654",
                            "opacity",
                            7500,
                            0,
                            "swing",
                            "${redtrng2}",
                            '0',
                            '1'
                        ],
                        [
                            "eid650",
                            "opacity",
                            7750,
                            0,
                            "swing",
                            "${redtrng2}",
                            '1',
                            '0'
                        ],
                        [
                            "eid656",
                            "opacity",
                            8000,
                            0,
                            "swing",
                            "${redtrng2}",
                            '0',
                            '1'
                        ],
                        [
                            "eid651",
                            "opacity",
                            8250,
                            0,
                            "swing",
                            "${redtrng2}",
                            '1',
                            '0'
                        ],
                        [
                            "eid658",
                            "opacity",
                            8500,
                            0,
                            "swing",
                            "${redtrng2}",
                            '0',
                            '1'
                        ],
                        [
                            "eid516",
                            "height",
                            5000,
                            250,
                            "swing",
                            "${jomalone}",
                            '7px',
                            '30px'
                        ],
                        [
                            "eid1033",
                            "height",
                            6000,
                            0,
                            "linear",
                            "${jomalone}",
                            '30px',
                            '30px'
                        ],
                        [
                            "eid1034",
                            "height",
                            6250,
                            0,
                            "linear",
                            "${jomalone}",
                            '30px',
                            '30px'
                        ],
                        [
                            "eid376",
                            "opacity",
                            2843,
                            250,
                            "easeInBack",
                            "${_2cuttitle_5_02}",
                            '0',
                            '1'
                        ],
                        [
                            "eid664",
                            "top",
                            6000,
                            0,
                            "swing",
                            "${PD}",
                            '71px',
                            '71px'
                        ],
                        [
                            "eid665",
                            "top",
                            6250,
                            0,
                            "swing",
                            "${PD}",
                            '71px',
                            '71px'
                        ],
                        [
                            "eid919",
                            "left",
                            2500,
                            250,
                            "swing",
                            "${_2cuttitle1}",
                            '-214px',
                            '6px'
                        ],
                        [
                            "eid509",
                            "left",
                            4750,
                            250,
                            "swing",
                            "${PLUS}",
                            '-180px',
                            '38px'
                        ],
                        [
                            "eid549",
                            "left",
                            6000,
                            250,
                            "swing",
                            "${PLUS}",
                            '38px',
                            '-182px'
                        ],
                        [
                            "eid1078",
                            "width",
                            2500,
                            0,
                            "easeInBack",
                            "${Group2}",
                            '143px',
                            '143px'
                        ],
                        [
                            "eid1082",
                            "width",
                            2750,
                            0,
                            "easeInBack",
                            "${Group2}",
                            '143px',
                            '143px'
                        ],
                        [
                            "eid1087",
                            "width",
                            6000,
                            0,
                            "easeInBack",
                            "${Group2}",
                            '143px',
                            '143px'
                        ],
                        [
                            "eid1089",
                            "width",
                            6250,
                            0,
                            "easeInBack",
                            "${Group2}",
                            '143px',
                            '143px'
                        ],
                        [
                            "eid399",
                            "top",
                            3000,
                            250,
                            "swing",
                            "${number1}",
                            '157px',
                            '150px'
                        ],
                        [
                            "eid679",
                            "top",
                            4500,
                            250,
                            "swing",
                            "${number1}",
                            '150px',
                            '152px'
                        ],
                        [
                            "eid703",
                            "top",
                            6500,
                            0,
                            "swing",
                            "${_100bat}",
                            '141px',
                            '141px'
                        ],
                        [
                            "eid704",
                            "top",
                            6750,
                            0,
                            "swing",
                            "${_100bat}",
                            '141px',
                            '141px'
                        ],
                        [
                            "eid645",
                            "opacity",
                            7000,
                            0,
                            "swing",
                            "${redtrng}",
                            '0',
                            '0'
                        ],
                        [
                            "eid653",
                            "opacity",
                            7250,
                            0,
                            "swing",
                            "${redtrng}",
                            '0',
                            '1'
                        ],
                        [
                            "eid649",
                            "opacity",
                            7500,
                            0,
                            "swing",
                            "${redtrng}",
                            '1',
                            '0'
                        ],
                        [
                            "eid655",
                            "opacity",
                            7750,
                            0,
                            "swing",
                            "${redtrng}",
                            '0',
                            '1'
                        ],
                        [
                            "eid652",
                            "opacity",
                            8000,
                            0,
                            "swing",
                            "${redtrng}",
                            '1',
                            '0'
                        ],
                        [
                            "eid657",
                            "opacity",
                            8250,
                            0,
                            "swing",
                            "${redtrng}",
                            '0',
                            '1'
                        ],
                        [
                            "eid595",
                            "left",
                            6500,
                            250,
                            "swing",
                            "${_100bat}",
                            '-87px',
                            '138px'
                        ],
                        [
                            "eid193",
                            "opacity",
                            250,
                            750,
                            "easeInBack",
                            "${D_11_subtitle}",
                            '0',
                            '1'
                        ],
                        [
                            "eid292",
                            "opacity",
                            2500,
                            250,
                            "easeInCirc",
                            "${D_11_subtitle}",
                            '1',
                            '0'
                        ],
                        [
                            "eid609",
                            "top",
                            2500,
                            250,
                            "swing",
                            "${TOPBLACK}",
                            '-30px',
                            '0px'
                        ],
                        [
                            "eid946",
                            "height",
                            3147,
                            0,
                            "swing",
                            "${giftcard}",
                            '18px',
                            '18px'
                        ],
                        [
                            "eid952",
                            "height",
                            3343,
                            0,
                            "swing",
                            "${giftcard}",
                            '18px',
                            '18px'
                        ],
                        [
                            "eid953",
                            "height",
                            4500,
                            0,
                            "swing",
                            "${giftcard}",
                            '18px',
                            '18px'
                        ],
                        [
                            "eid954",
                            "height",
                            4750,
                            0,
                            "swing",
                            "${giftcard}",
                            '18px',
                            '18px'
                        ],
                        [
                            "eid510",
                            "top",
                            4750,
                            250,
                            "swing",
                            "${PLUS}",
                            '153px',
                            '154px'
                        ],
                        [
                            "eid705",
                            "top",
                            6000,
                            250,
                            "swing",
                            "${PLUS}",
                            '154px',
                            '151px'
                        ],
                        [
                            "eid235",
                            "left",
                            2500,
                            250,
                            "swing",
                            "${topsubtitle}",
                            '393px',
                            '113px'
                        ],
                        [
                            "eid352",
                            "top",
                            2593,
                            250,
                            "swing",
                            "${_2cuttitle_5_01}",
                            '106px',
                            '93px'
                        ],
                        [
                            "eid366",
                            "top",
                            2843,
                            250,
                            "swing",
                            "${_2cuttitle_5_01}",
                            '93px',
                            '83px'
                        ],
                        [
                            "eid367",
                            "top",
                            3093,
                            250,
                            "swing",
                            "${_2cuttitle_5_01}",
                            '83px',
                            '93px'
                        ],
                        [
                            "eid569",
                            "width",
                            6500,
                            0,
                            "swing",
                            "${_100bat}",
                            '73px',
                            '73px'
                        ],
                        [
                            "eid581",
                            "width",
                            6750,
                            0,
                            "swing",
                            "${_100bat}",
                            '73px',
                            '73px'
                        ],
                        [
                            "eid229",
                            "height",
                            2500,
                            250,
                            "swing",
                            "${TOPBLACK}",
                            '23px',
                            '42px'
                        ],
                        [
                            "eid1079",
                            "height",
                            2500,
                            0,
                            "easeInBack",
                            "${Group2}",
                            '198px',
                            '198px'
                        ],
                        [
                            "eid1083",
                            "height",
                            2750,
                            0,
                            "easeInBack",
                            "${Group2}",
                            '198px',
                            '198px'
                        ],
                        [
                            "eid1088",
                            "height",
                            6000,
                            0,
                            "easeInBack",
                            "${Group2}",
                            '198px',
                            '198px'
                        ],
                        [
                            "eid1090",
                            "height",
                            6250,
                            0,
                            "easeInBack",
                            "${Group2}",
                            '198px',
                            '198px'
                        ],
                        [
                            "eid397",
                            "width",
                            3000,
                            250,
                            "swing",
                            "${number1}",
                            '7px',
                            '24px'
                        ],
                        [
                            "eid453",
                            "width",
                            4500,
                            0,
                            "swing",
                            "${number1}",
                            '24px',
                            '24px'
                        ],
                        [
                            "eid459",
                            "width",
                            4750,
                            0,
                            "swing",
                            "${number1}",
                            '24px',
                            '24px'
                        ],
                        [
                            "eid485",
                            "height",
                            4750,
                            0,
                            "swing",
                            "${PLUS}",
                            '18px',
                            '18px'
                        ],
                        [
                            "eid499",
                            "height",
                            5000,
                            0,
                            "swing",
                            "${PLUS}",
                            '18px',
                            '18px'
                        ],
                        [
                            "eid522",
                            "height",
                            6000,
                            0,
                            "swing",
                            "${PLUS}",
                            '18px',
                            '18px'
                        ],
                        [
                            "eid540",
                            "height",
                            6250,
                            0,
                            "swing",
                            "${PLUS}",
                            '18px',
                            '18px'
                        ],
                        [
                            "eid1001",
                            "top",
                            0,
                            0,
                            "easeInBack",
                            "${Group}",
                            '30px',
                            '30px'
                        ],
                        [
                            "eid1003",
                            "top",
                            500,
                            0,
                            "easeInBack",
                            "${Group}",
                            '30px',
                            '30px'
                        ],
                        [
                            "eid1010",
                            "top",
                            2500,
                            0,
                            "easeInBack",
                            "${Group}",
                            '30px',
                            '30px'
                        ],
                        [
                            "eid1014",
                            "top",
                            2750,
                            0,
                            "easeInBack",
                            "${Group}",
                            '30px',
                            '30px'
                        ],
                        [
                            "eid998",
                            "width",
                            0,
                            0,
                            "easeInBack",
                            "${Group}",
                            '143px',
                            '143px'
                        ],
                        [
                            "eid1004",
                            "width",
                            500,
                            0,
                            "easeInBack",
                            "${Group}",
                            '143px',
                            '143px'
                        ],
                        [
                            "eid1007",
                            "width",
                            2500,
                            0,
                            "easeInBack",
                            "${Group}",
                            '143px',
                            '143px'
                        ],
                        [
                            "eid1011",
                            "width",
                            2750,
                            0,
                            "easeInBack",
                            "${Group}",
                            '143px',
                            '143px'
                        ],
                        [
                            "eid695",
                            "top",
                            6000,
                            0,
                            "swing",
                            "${number3}",
                            '148px',
                            '148px'
                        ],
                        [
                            "eid696",
                            "top",
                            6250,
                            0,
                            "swing",
                            "${number3}",
                            '148px',
                            '148px'
                        ],
                        [
                            "eid1077",
                            "top",
                            2500,
                            0,
                            "easeInBack",
                            "${Group2}",
                            '43px',
                            '43px'
                        ],
                        [
                            "eid1081",
                            "top",
                            2750,
                            0,
                            "easeInBack",
                            "${Group2}",
                            '43px',
                            '43px'
                        ],
                        [
                            "eid1086",
                            "top",
                            6000,
                            0,
                            "easeInBack",
                            "${Group2}",
                            '43px',
                            '43px'
                        ],
                        [
                            "eid1092",
                            "top",
                            6250,
                            0,
                            "easeInBack",
                            "${Group2}",
                            '43px',
                            '43px'
                        ],
                        [
                            "eid380",
                            "width",
                            2843,
                            250,
                            "easeInBack",
                            "${_2cuttitle_5_02}",
                            '11px',
                            '31px'
                        ],
                        [
                            "eid381",
                            "width",
                            3093,
                            250,
                            "easeInBack",
                            "${_2cuttitle_5_02}",
                            '31px',
                            '38px'
                        ],
                        [
                            "eid382",
                            "width",
                            3343,
                            250,
                            "easeInBack",
                            "${_2cuttitle_5_02}",
                            '38px',
                            '31px'
                        ],
                        [
                            "eid629",
                            "opacity",
                            6750,
                            250,
                            "swing",
                            "${BTN}",
                            '0',
                            '1'
                        ],
                        [
                            "eid423",
                            "height",
                            3343,
                            196,
                            "swing",
                            "${gift1700}",
                            '7px',
                            '30px'
                        ],
                        [
                            "eid963",
                            "height",
                            4500,
                            0,
                            "swing",
                            "${gift1700}",
                            '30px',
                            '30px'
                        ],
                        [
                            "eid964",
                            "height",
                            4750,
                            0,
                            "swing",
                            "${gift1700}",
                            '30px',
                            '30px'
                        ]
                    ]
                }
            }
        };

    AdobeEdge.registerCompositionDefn(compId, symbols, fonts, scripts, resources, opts);

    if (!window.edge_authoring_mode) AdobeEdge.getComposition(compId).load("20161123_edgeActions.js");
})("EDGE-45488995");
